#!/usr/bin/env bash
# Tests for the generated gstack skills under shared/skills/.
#
# gstack-patch.test.sh proves the filter is correct. This suite proves the
# CHECKED-IN OUTPUT is correct, which is a different claim: the files in
# shared/skills/ are committed, they are what actually loads into a session,
# and nothing stops someone editing one by hand or a sync running against a
# moved pin and quietly changing them.
#
# The whole reason the patched skills are versioned rather than generated on
# each machine is so that a change to them shows up in a diff. That only helps
# if something also checks the diff is the one we meant, so this suite is the
# check: it re-derives every skill from third_party/ and fails if the committed file
# disagrees.
#
# When third_party/ is absent — a fresh clone, or CI — the re-derivation is skipped
# and the suite still verifies everything that can be known from the committed
# files alone. That degradation is deliberate: a test that can only run after a
# 42 MB clone and a Bun build is a test that never runs.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS="$REPO/shared/skills"
VENDOR="$REPO/third_party/gstack"
PATCH="$REPO/scripts/gstack-patch.sh"
PIN="$REPO/GSTACK_PIN"

# The fifteen skills adopted from gstack, and the reason each one earned its
# place. They were chosen because nothing in this configuration already covers
# them; the families that DID overlap (planning, design system, memory, docs,
# security, PDF, release) were rejected on purpose, and adding one back here
# without removing its local counterpart would put two skills in competition
# for the same trigger.
GSTACK_SKILLS=(
  browse scrape                        # headless Chromium, no local equivalent
  qa qa-only                           # real-browser QA and regression tests
  careful freeze guard unfreeze        # guardrails, 12 KB all in
  investigate diagram                  # hypothesis debugging, mermaid from prose
  canary benchmark retro               # post-deploy watch, Core Web Vitals
  land-and-deploy                      # the tranche after ship stops at the PR
  design-shotgun                       # parallel variants + taste memory
)

pass=0
fail=0

ok() { printf '  \033[32mPASS\033[0m %s\n' "$1"; pass=$((pass + 1)); }
ko() { printf '  \033[31mFAIL\033[0m %s\n     expected: %s\n     actual:   %s\n' "$1" "$2" "$3"; fail=$((fail + 1)); }
assert_eq() { [ "$2" = "$3" ] && ok "$1" || ko "$1" "$2" "$3"; }

echo "gstack-skills"

# --- the pin -----------------------------------------------------------------
# An unpinned checkout makes the committed skills unreproducible: re-running sync
# against a moved upstream silently rewrites them, and the diff that shows up
# is attributed to nobody.
assert_eq "GSTACK_PIN exists" "yes" "$([ -f "$PIN" ] && echo yes || echo no)"
if [ -f "$PIN" ]; then
  pin_sha="$(rg -o '^[0-9a-f]{40}$' "$PIN" | head -1)"
  assert_eq "GSTACK_PIN holds a full 40-char commit sha" "yes" \
    "$([ -n "$pin_sha" ] && echo yes || echo no)"
fi

# --- every adopted skill is present ------------------------------------------
missing=0
for s in "${GSTACK_SKILLS[@]}"; do
  [ -f "$SKILLS/$s/SKILL.md" ] || { echo "     missing: shared/skills/$s/SKILL.md"; missing=1; }
done
assert_eq "every adopted skill is checked in" "0" "$missing"

# --- they are all marked as generated ----------------------------------------
# They sit beside hand-written skills. Without the marker the next person to
# open one edits it, and the edit disappears on the next sync.
unmarked=0
for s in "${GSTACK_SKILLS[@]}"; do
  f="$SKILLS/$s/SKILL.md"
  [ -f "$f" ] || continue
  rg -q 'generated by scripts/gstack-patch.sh' "$f" || { echo "     unmarked: $s"; unmarked=1; }
done
assert_eq "every generated skill carries the provenance header" "0" "$unmarked"

# --- no colliding section survived -------------------------------------------
# The point of the whole exercise. A single one of these coming back means a
# session runs with two sets of rules and picks between them.
leaked=0
for s in "${GSTACK_SKILLS[@]}"; do
  f="$SKILLS/$s/SKILL.md"
  [ -f "$f" ] || continue
  for h in "Voice" "Continuous Checkpoint Mode" "Question Tuning" "Telemetry" \
           "Artifacts Sync" "Brain Context" "Operational Self-Improvement" \
           "Plan Status Footer" "AskUserQuestion Format" "Preamble" \
           "Writing Style" "Model-Specific Behavioral Patch" \
           "Skill Invocation During Plan Mode"; do
    if rg -q "^## $h" "$f"; then
      echo "     $s still carries: ## $h"
      leaked=1
    fi
  done
done
assert_eq "no stripped section survives in any generated skill" "0" "$leaked"

# --- runtime paths point at the vendored install -----------------------------
stale=0
for s in "${GSTACK_SKILLS[@]}"; do
  f="$SKILLS/$s/SKILL.md"
  [ -f "$f" ] || continue
  rg -q '\.claude/skills/gstack' "$f" && { echo "     $s points at the upstream install path"; stale=1; }
done
assert_eq "no skill points at the upstream install path" "0" "$stale"

# --- frontmatter is intact ---------------------------------------------------
# A mangled frontmatter does not error, it just makes the skill undiscoverable.
bad_fm=0
for s in "${GSTACK_SKILLS[@]}"; do
  f="$SKILLS/$s/SKILL.md"
  [ -f "$f" ] || continue
  [ "$(head -1 "$f")" = "---" ] || { echo "     $s does not open with ---"; bad_fm=1; continue; }
  rg -q '^name:' "$f" || { echo "     $s has no name: field"; bad_fm=1; }
  rg -q '^description:|^description :' "$f" || { echo "     $s has no description: field"; bad_fm=1; }
done
assert_eq "every generated skill has usable frontmatter" "0" "$bad_fm"

# --- names are unique against the hand-written skills ------------------------
# The fan-out links every subdirectory of shared/skills into three agent skill
# directories. Two skills claiming one name is a silent overwrite, and which
# one wins depends on directory order.
dupes=0
for s in "${GSTACK_SKILLS[@]}"; do
  for own in ship pdf-report product-demo-video repo-prep; do
    [ "$s" = "$own" ] && { echo "     $s collides with the hand-written $own"; dupes=1; }
  done
done
assert_eq "no adopted skill collides with a hand-written one" "0" "$dupes"

# --- the committed files match what the patch produces -----------------------
# The drift check, and the reason versioning these files buys anything. Skipped
# without third_party/, which is gitignored and absent on a fresh clone.
if [ -d "$VENDOR" ] && [ -x "$PATCH" ]; then
  drifted=0
  for s in "${GSTACK_SKILLS[@]}"; do
    src="$VENDOR/$s/SKILL.md"
    committed="$SKILLS/$s/SKILL.md"
    [ -f "$src" ] && [ -f "$committed" ] || continue
    if ! "$PATCH" "$src" | cmp -s - "$committed"; then
      echo "     $s differs from a fresh patch of third_party — re-run scripts/gstack-sync.sh"
      drifted=1
    fi
  done
  assert_eq "every committed skill matches a fresh patch of third_party" "0" "$drifted"
else
  printf '  \033[33mSKIP\033[0m drift check (third_party/gstack absent — run scripts/gstack-sync.sh)\n'
fi

printf '\n%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
