#!/usr/bin/env bash
# Strip the colliding sections out of a gstack SKILL.md.
#
# gstack skills above tier 2 carry ~31 KB of shared preamble — in `canary` that
# is 72% of the file, in `investigate` 70%. Most of it is not task instruction
# but house doctrine: a voice, a commit discipline, a question format and a
# memory system. This configuration already has all four, and they disagree, so
# loading such a skill unpatched puts two sets of rules in one context and lets
# the model pick. That is not a style preference; it is a correctness problem.
#
# So this filter removes the sections that collide and leaves everything else
# alone. What it removes and why is documented in tests/gstack-patch.test.sh —
# the tests are the specification, this is the implementation.
#
# Usage:  gstack-patch.sh <path/to/SKILL.md>   # patched file on stdout
set -uo pipefail

SRC="${1:-}"

if [ -z "$SRC" ]; then
  printf 'usage: %s <path/to/SKILL.md>\n' "$(basename "$0")" >&2
  exit 2
fi

if [ ! -f "$SRC" ]; then
  printf '%s: no such file: %s\n' "$(basename "$0")" "$SRC" >&2
  exit 1
fi

# Sections removed, matched on the heading PREFIX.
#
# Prefix rather than exact match because upstream appends parentheticals that
# change between versions: "## Telemetry (run last)", "## Question Tuning (skip
# entirely if `QUESTION_TUNING: false`)", "## Artifacts Sync (skill start)". An
# exact-match list would silently stop matching the first time upstream
# reworded a suffix, and a section would come back without anyone noticing.
# Prefix matching also catches the variants — "Voice" covers "Voice & Tone" in
# land-and-deploy, which is the same doctrine under a longer name.
STRIP=(
  # --- rival doctrine: collides with CLAUDE.md ---
  "Voice"                            # a house voice over the configured persona
  "Continuous Checkpoint Mode"       # auto-commits WIP, against work-unit-commits
  "Question Tuning"                  # its own question format, against one-at-a-time
  "Telemetry"                        # runs gstack-skill-end at skill close
  "Artifacts Sync"                   # drains a queue into gstack's own store
  "Brain Context"                    # reads GBrain, a second memory beside engram
  "Operational Self-Improvement"     # lets the skill rewrite its own file
  "Plan Status Footer"               # appends a status block to every reply

  # --- dead code in a vendored install ---
  # These address infrastructure that only exists inside a full gstack setup.
  # Here they are not merely redundant, they are broken or inert.
  #
  # AskUserQuestion Format is the single heaviest section in a tier-3 skill —
  # 10.9 KB of 40 KB in canary — and every byte of it resolves tooling
  # (Conductor, plan-tune, question-log, spawned-session auto-decide) that is
  # not installed here.
  #
  # Preamble execs gstack-skill-start from ~/.claude/skills/gstack/bin/, a path
  # a vendored install never creates. It therefore fails on every invocation,
  # and it is also the channel through which GSTACK_INSTRUCTION_BEGIN blocks
  # deliver one-time onboarding and consent directives.
  "AskUserQuestion Format"
  "Preamble"
  "Writing Style"
  "Model-Specific Behavioral Patch"
  "Skill Invocation During Plan Mode"
)

# Sections that must survive even if a future entry above would match them.
#
# Context Recovery is how a skill resumes after a compaction, and Search Before
# Building is what stops it reimplementing code that already exists. Both are
# load-bearing and neither collides with anything here. The keep list is
# checked first so that broadening a strip prefix can never take one out by
# accident.
KEEP=(
  "Context Recovery"
  "Search Before Building"
)

MARKER="generated by scripts/gstack-patch.sh"

# Whether the input already carries a provenance header, decided here rather
# than inside awk.
#
# awk sees the file as a stream, and the first line after the frontmatter of an
# already-patched file is the blank line the header is preceded by — not the
# header itself. Testing that one line therefore always missed, and every
# re-run stacked another header on top. sync re-runs this filter over its own
# output whenever the pin moves, so that drift would have been permanent.
if rg -qF "$MARKER" "$SRC" 2>/dev/null; then
  ALREADY_PATCHED=1
else
  ALREADY_PATCHED=0
fi

# Repoint every runtime path at the vendored install.
#
# The skills reach their own binaries and reference files through
# ~/.claude/skills/gstack/ — where upstream's ./setup plants the whole repo.
# This install deliberately does not do that: only the fifteen chosen skills go
# into the skills directory, and the 42 MB runtime stays in third_party/. Left
# alone, roughly 110 references across those fifteen files would resolve to
# nothing, and not decoratively: qa opens by shelling out to gstack-config, and
# reads half its body out of qa/sections/.
#
# So they are rewritten to ~/.gstack, a stable symlink that gstack-sync.sh
# points at third_party/gstack. Going through a fixed path in $HOME rather than
# the repo's own location means the generated skills stay identical whatever
# directory the repo is cloned into — which is what lets them be committed.
#
# The substitution is on the path fragment alone, so it catches every spelling
# in use (`~/`, `$HOME/`, `$_ROOT/`) without touching the surrounding text.
repoint_runtime_paths() {
  sd -s '.claude/skills/gstack' '.gstack'
}

# The lists reach awk pipe-separated, not newline-separated: the awk shipped
# with macOS rejects a literal newline inside a -v assignment ("newline in
# string"), and this repo has to run on macOS and Linux from the same file. No
# section title contains a pipe.
awk -v strip_list="$(IFS='|'; printf '%s' "${STRIP[*]}")" \
    -v keep_list="$(IFS='|'; printf '%s' "${KEEP[*]}")" \
    -v marker="$MARKER" \
    -v already_patched="$ALREADY_PATCHED" '
BEGIN {
  n_strip = split(strip_list, strip, "|")
  n_keep  = split(keep_list, keep, "|")
  in_frontmatter = 0
  frontmatter_done = 0
  in_fence = 0
  skipping = 0
  header_emitted = 0
}

# --- frontmatter -------------------------------------------------------------
# Passed through byte for byte. Claude Code reads name: and description: from
# this block, and a mangled one does not fail loudly — the skill just stops
# being discovered.
NR == 1 && $0 == "---" { in_frontmatter = 1; print; next }
in_frontmatter && $0 == "---" {
  in_frontmatter = 0
  frontmatter_done = 1
  print
  next
}
in_frontmatter { print; next }

# --- provenance header -------------------------------------------------------
# Emitted immediately after the frontmatter, never before it: a comment above
# the opening delimiter stops the block being frontmatter at all.
#
# Suppressed when the input already carries one, which is what makes the filter
# idempotent — sync re-runs it over its own output every time the pin moves.
frontmatter_done && !header_emitted {
  header_emitted = 1
  if (already_patched == 0) {
    print ""
    print "<!-- " marker " from gstack upstream. Do not edit by hand:"
    print "     changes are lost on the next scripts/gstack-sync.sh run. -->"
  }
}

# --- fenced code blocks ------------------------------------------------------
# Tracked so that a "## something" inside a code sample is never mistaken for a
# heading. Several gstack skills embed markdown in their examples, and without
# this the filter would start skipping at a line of sample text and swallow the
# rest of the real section.
/^[[:space:]]*```/ { in_fence = !in_fence; if (!skipping) print; next }
in_fence { if (!skipping) print; next }

# --- section boundaries ------------------------------------------------------
/^## / {
  title = substr($0, 4)

  # Keep list wins over the strip list, always.
  is_keep = 0
  for (i = 1; i <= n_keep; i++) {
    if (keep[i] != "" && index(title, keep[i]) == 1) { is_keep = 1; break }
  }

  is_strip = 0
  if (!is_keep) {
    for (i = 1; i <= n_strip; i++) {
      if (strip[i] != "" && index(title, strip[i]) == 1) { is_strip = 1; break }
    }
  }

  skipping = is_strip
  if (skipping) next
}

# A level-1 heading ends any section being skipped: skipping runs until the
# next heading of equal or higher rank, not to end of file.
/^# / { skipping = 0 }

{ if (!skipping) print }
' "$SRC" | repoint_runtime_paths
