#!/usr/bin/env python3
"""Generate the README hero: suminagashi ink rings in the Tokyo Night palette.

    python3 docs/hero.py > docs/assets/hero.svg
    rsvg-convert -w 2400 docs/assets/hero.svg -o docs/assets/hero.png

Suminagashi (墨流し, "floating ink") is made by touching concentric rings of ink
onto still water and then disturbing the surface, so every ring deforms along
the same currents while staying nested. This reproduces that: rings are laid
down as polygons, then each vertex is displaced by a shared field, so the
distortion is coherent across rings rather than random per ring — which is the
difference between marbled ink and noise.

Deterministic by design. A fixed seed means the hero can be regenerated byte for
byte, and a change to the image is a change someone made on purpose.
"""

import math
import random

# Canvas. 3:1 is about as tall as a README hero can be before it pushes the
# first line of prose off a laptop screen.
W, H = 1200, 400
SEED = 20260825

# Tokyo Night. The same palette as the installer TUI and the terminal this repo
# configures, so the hero belongs to the same world as the thing it introduces.
BG = "#1a1b26"
INKS = [
    ("#7aa2f7", 0.95),  # blue
    ("#7dcfff", 0.80),  # cyan
    ("#bb9af7", 0.78),  # magenta
    ("#2ac3de", 0.70),  # teal
    ("#9ece6a", 0.40),  # green, sparingly: it reads as "success" elsewhere
]

rng = random.Random(SEED)


def currents(n):
    """A shared displacement field.

    Every ring is deformed by these same waves, which is what makes the result
    read as one disturbed surface instead of a stack of unrelated squiggles.
    """
    return [
        {
            "freq": rng.uniform(0.5, 2.8),
            "amp": rng.uniform(14, 52),
            "phase": rng.uniform(0, math.tau),
            "skew": rng.uniform(-0.4, 0.4),
        }
        for _ in range(n)
    ]


FIELD = currents(5)


def displace(x, y, angle, radius):
    """Push one vertex along the currents.

    The displacement grows with radius: ink further from the drop point has had
    longer to travel, so outer rings distort more than inner ones.
    """
    scale = 0.35 + radius / 260.0
    dx = dy = 0.0
    for c in FIELD:
        wave = math.sin(angle * c["freq"] + c["phase"])
        dx += math.cos(angle + c["skew"]) * wave * c["amp"] * scale
        dy += math.sin(angle + c["skew"]) * wave * c["amp"] * scale * 0.45
    # A slow horizontal drift, as though the tray were tilted while setting.
    dx += math.sin(y / 90.0) * 14
    return dx, dy


def ring(cx, cy, radius, points=220):
    """One ink ring as an SVG path, flattened and deformed."""
    coords = []
    for i in range(points):
        a = (i / points) * math.tau
        # Rings are ellipses before deformation: ink spreads wider than it
        # travels on a shallow tray.
        x = cx + math.cos(a) * radius * 1.9
        y = cy + math.sin(a) * radius * 0.62
        dx, dy = displace(x, y, a, radius)
        coords.append((x + dx, y + dy))

    d = f"M {coords[0][0]:.1f} {coords[0][1]:.1f}"
    # Quadratic segments through midpoints: straight lines between 220 vertices
    # look faceted at hero size, and ink has no corners.
    for i in range(1, len(coords)):
        x0, y0 = coords[i - 1]
        x1, y1 = coords[i]
        mx, my = (x0 + x1) / 2, (y0 + y1) / 2
        d += f" Q {x0:.1f} {y0:.1f} {mx:.1f} {my:.1f}"
    return d + " Z"


def drop(cx, cy, count, step, colour, base_alpha):
    """A single touch of the brush: `count` nested rings from one point."""
    out = []
    for i in range(count):
        r = 8 + i * step
        # Outer rings are fainter: the ink thins as it spreads.
        alpha = base_alpha * (1 - i / (count * 1.6))
        width = 2.0 if i % 3 else 3.0
        out.append(
            f'<path d="{ring(cx, cy, r)}" fill="none" stroke="{colour}" '
            f'stroke-width="{width}" stroke-opacity="{alpha:.3f}" '
            f'stroke-linejoin="round"/>'
        )
    return out


def build():
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'width="{W}" height="{H}" role="img" '
        f'aria-label="Alvaro\'s Dotfiles">',
        "<defs>",
        # A vignette so the ink fades at the edges instead of being cropped,
        # which is what a real tray looks like.
        '<radialGradient id="vig" cx="50%" cy="50%" r="72%">',
        '<stop offset="55%" stop-color="#ffffff" stop-opacity="1"/>',
        '<stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>',
        "</radialGradient>",
        '<mask id="fade"><rect width="100%" height="100%" fill="url(#vig)"/></mask>',
        # Shadow for the title to sit in, falling off to nothing at the edges.
        '<radialGradient id="scrim" cx="50%" cy="50%" r="50%">',
        f'<stop offset="0%" stop-color="{BG}" stop-opacity="0.92"/>',
        f'<stop offset="65%" stop-color="{BG}" stop-opacity="0.72"/>',
        f'<stop offset="100%" stop-color="{BG}" stop-opacity="0"/>',
        "</radialGradient>",
        "</defs>",
        f'<rect width="100%" height="100%" fill="{BG}"/>',
        '<g mask="url(#fade)">',
    ]

    # Drop points spread across the canvas, weighted away from dead centre so
    # the title has somewhere quiet to sit.
    drops = [
        (205, 195, 13, 19, 0),
        (995, 200, 12, 21, 1),
        (600, 105, 8, 17, 2),
        (620, 315, 7, 16, 3),
        (395, 245, 6, 15, 1),
        (820, 150, 6, 15, 2),
        (95, 315, 5, 14, 4),
        (1105, 95, 5, 14, 0),
    ]
    for cx, cy, count, step, ink in drops:
        colour, alpha = INKS[ink]
        parts.extend(drop(cx, cy, count, step, colour, alpha))

    parts.append("</g>")

    # A pool of shadow behind the words rather than a flat scrim over
    # everything: the title has to win, but dimming the whole canvas to achieve
    # that drains the ink at the edges where it is doing the most work.
    parts.append(
        f'<ellipse cx="{W/2}" cy="{H*0.55}" rx="{W*0.42}" ry="{H*0.34}" '
        f'fill="url(#scrim)"/>'
    )

    font = (
        "ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',"
        "Helvetica,Arial,sans-serif"
    )
    mono = "ui-monospace,SFMono-Regular,Menlo,Consolas,monospace"

    parts += [
        f'<text x="50%" y="47%" text-anchor="middle" font-family="{font}" '
        f'font-size="76" font-weight="800" fill="#c0caf5" '
        f'letter-spacing="-2">Álvaro\'s Dotfiles</text>',
        f'<text x="50%" y="64%" text-anchor="middle" font-family="{mono}" '
        f'font-size="22" fill="#7dcfff" letter-spacing="6">'
        f'TMUX · YAZI · GHOSTTY · CLAUDE CODE</text>',
        "</svg>",
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    print(build())
